/**
 * Lesson Data - Ukrainian
 *
 * Ukrainian translations for lesson titles and descriptions.
 * Structure mirrors lessons.ts for type safety.
 */

import type { Lesson } from "./lessons";

export const LESSONS_UK: Lesson[] = [
  {
    id: 0,
    slug: "welcome",
    title: "Ласкаво просимо",
    description: "Огляд того, що ви маєте і що вивчите",
    duration: "5 хв",
    file: "00_welcome.md",
  },
  {
    id: 1,
    slug: "linux-basics",
    title: "Навігація Linux",
    description: "Впевнено орієнтуйтесь у файловій системі",
    duration: "8 хв",
    file: "01_linux_basics.md",
  },
  {
    id: 2,
    slug: "ssh-basics",
    title: "SSH та постійні з'єднання",
    description: "Безпечні підключення та стабільний зв'язок",
    duration: "6 хв",
    file: "02_ssh_basics.md",
  },
  {
    id: 3,
    slug: "tmux-basics",
    title: "Основи tmux",
    description: "Зберігайте роботу при відключенні",
    duration: "7 хв",
    file: "03_tmux_basics.md",
  },
  {
    id: 4,
    slug: "git-basics",
    title: "Основи Git",
    description: "Контроль версій та небезпечні операції",
    duration: "10 хв",
    file: "04_git_basics.md",
  },
  {
    id: 5,
    slug: "github-cli",
    title: "GitHub CLI",
    description: "Керування issues, PR, релізами та actions",
    duration: "8 хв",
    file: "05_github_cli.md",
  },
  {
    id: 6,
    slug: "agent-commands",
    title: "Команди агентів",
    description: "Спілкування з Claude, Codex та Gemini",
    duration: "10 хв",
    file: "06_agents_login.md",
  },
  {
    id: 7,
    slug: "ntm-core",
    title: "NTM Command Center",
    description: "Оркестрація термінальних сесій",
    duration: "8 хв",
    file: "07_ntm_core.md",
  },
  {
    id: 8,
    slug: "ntm-palette",
    title: "NTM Prompt Palette",
    description: "Швидкий доступ до частих команд",
    duration: "6 хв",
    file: "08_ntm_command_palette.md",
  },
  {
    id: 9,
    slug: "flywheel-loop",
    title: "Flywheel Loop",
    description: "Об'єднайте все для максимальної швидкості",
    duration: "10 хв",
    file: "09_flywheel_loop.md",
  },
  {
    id: 10,
    slug: "keeping-updated",
    title: "Оновлення системи",
    description: "Підтримка та оновлення середовища",
    duration: "4 хв",
    file: "10_keeping_updated.md",
  },
  {
    id: 11,
    slug: "ubs",
    title: "UBS: Якість коду",
    description: "Ловіть баги до продакшену",
    duration: "8 хв",
    file: "11_ubs.md",
  },
  {
    id: 12,
    slug: "agent-mail",
    title: "Agent Mail",
    description: "Координація агентів та резервування файлів",
    duration: "10 хв",
    file: "12_agent_mail.md",
  },
  {
    id: 13,
    slug: "cass",
    title: "CASS: Історія сесій",
    description: "Пошук по всіх минулих сесіях агентів",
    duration: "8 хв",
    file: "13_cass.md",
  },
  {
    id: 14,
    slug: "cm",
    title: "Система пам'яті",
    description: "Процедурна пам'ять для агентів",
    duration: "8 хв",
    file: "14_cm.md",
  },
  {
    id: 15,
    slug: "beads",
    title: "Beads: Трекінг задач",
    description: "Управління задачами з залежностями",
    duration: "8 хв",
    file: "15_beads.md",
  },
  {
    id: 16,
    slug: "safety-tools",
    title: "Безпека: SLB та CAAM",
    description: "Правило двох осіб та керування акаунтами",
    duration: "6 хв",
    file: "16_safety_tools.md",
  },
  {
    id: 17,
    slug: "prompt-engineering",
    title: "Мистецтво промптів",
    description: "Паттерни промптів для відмінних результатів",
    duration: "12 хв",
    file: "17_prompt_engineering.md",
  },
  {
    id: 18,
    slug: "real-world-case-study",
    title: "Кейс: cass-memory",
    description: "Складний проєкт за день з agent swarms",
    duration: "15 хв",
    file: "18_real_world_case_study.md",
  },
  {
    id: 19,
    slug: "slb-case-study",
    title: "Кейс: SLB",
    description: "Від твіту до працюючого інструменту за вечір",
    duration: "12 хв",
    file: "19_slb_case_study.md",
  },
  {
    id: 20,
    slug: "ru",
    title: "RU: Майстерність багатьох репозиторіїв",
    description: "Синхронізація репозиторіїв та автоматизація комітів з AI",
    duration: "10 хв",
    file: "20_ru.md",
  },
  {
    id: 21,
    slug: "dcg",
    title: "DCG: Безпека перед виконанням",
    description: "Блокування небезпечних команд до того як вони завдадуть шкоди",
    duration: "8 хв",
    file: "21_dcg.md",
  },
  {
    id: 22,
    slug: "ms",
    title: "Meta Skill: Локальні Skills",
    description: "Керування та обмін Claude Code skills локально",
    duration: "10 хв",
    file: "22_meta_skill.md",
  },
  {
    id: 23,
    slug: "srps",
    title: "SRPS: Захист системи",
    description: "Підтримуйте чуйність робочої станції під час інтенсивного навантаження від агентів",
    duration: "8 хв",
    file: "23_srps.md",
  },
  {
    id: 24,
    slug: "jfp",
    title: "JFP: Пошук промптів",
    description: "Відкрийте та встановлюйте куровані промпти з JeffreysPrompts",
    duration: "6 хв",
    file: "24_jfp.md",
  },
  {
    id: 25,
    slug: "apr",
    title: "APR: Удосконалення планів",
    description: "Автоматизоване ітеративне покращення планів за допомогою AI",
    duration: "8 хв",
    file: "25_apr.md",
  },
  {
    id: 26,
    slug: "pt",
    title: "PT: Управління процесами",
    description: "Інтелектуальна сортування процесів та моніторинг ресурсів",
    duration: "6 хв",
    file: "26_pt.md",
  },
  {
    id: 27,
    slug: "xf",
    title: "XF: Пошук архіву Twitter",
    description: "Блискавично швидкий пошук по вашій історії X/Twitter",
    duration: "6 хв",
    file: "27_xf.md",
  },
  {
    id: 28,
    slug: "rch",
    title: "RCH: Remote Code Host",
    description: "Відвантажуйте збірки Rust на віддалені воркери для швидшої компіляції",
    duration: "8 хв",
    file: "28_rch.md",
  },
  {
    id: 29,
    slug: "wa",
    title: "WA: Wezterm Automata",
    description: "Координуйте кілька AI агентів з спостереженням терміналу в реальному часі",
    duration: "7 хв",
    file: "29_wa.md",
  },
  {
    id: 30,
    slug: "brenner",
    title: "Brenner: AI Bot Manager",
    description: "Оркеструйте та моніторте життєві цикли AI агентів",
    duration: "6 хв",
    file: "30_brenner.md",
  },
  {
    id: 31,
    slug: "giil",
    title: "GIIL: Завантаження хмарних зображень",
    description: "Завантажуйте хмарні зображення для візуального дебагу",
    duration: "6 хв",
    file: "31_giil.md",
  },
  {
    id: 32,
    slug: "s2p",
    title: "S2P: Вихідний код у промпт",
    description: "Об'єднуйте вихідний код у LLM-ready промпти з підрахунком токенів",
    duration: "6 хв",
    file: "32_s2p.md",
  },
];

export const TOTAL_LESSONS_UK = LESSONS_UK.length;
